### I think we are at the point where I need to outline my plan for this data. It will be important in understanding what to join and drop

#### Additional Data Options if interested in more (need a good reason, because you have  A LOT)
- Continue down artist path - join with kaggle dataset
    - https://www.kaggle.com/yamaerenay/spotify-dataset-19212020-160k-tracks?select=data_by_artist_o.csv
    - data_by_artist_o.csv
    - but this is by artist name... 
- Go down genre path
    - https://www.kaggle.com/yamaerenay/spotify-dataset-19212020-160k-tracks?select=data_by_artist_o.csv
    - data_by_genres_o.csv

In [1]:
# Basics 
import pandas as pd
import numpy as np

# Text Cleaning
import re

#Spotify
# Source: https://betterprogramming.pub/how-to-extract-any-artists-data-using-spotify-s-api-python-and-spotipy-4c079401bc37
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
import time 

# Importing dfs with heavy processing
import pickle

In [2]:
# import peloton data
# Thank you to okaykristinakay on Reddit for the data!
# Source: https://www.reddit.com/r/pelotoncycle/comments/m18xnr/peloton_class_list_march_update/
df = pd.read_excel('../AGF_Peloton Classes March.xlsx')
df.head()

,classId,className,classDescription,classDifficulty,classDuration,classType,classLength,classLocation,classOriginalAirdate,classRating,classRatingCount,instructorName,instructorBio,classEquipment,classSongs,classArtists,classUrl
0,7f66378211c9476b9b5619bf989f91d0,20 min Peace Meditation,A guided meditation that focuses on cultivatin...,4.3333,20,Meditation,23,psny-studio-2,2021-09-03 13:25:00,0.9847,131,Aditi Shah,"To Aditi, yoga goes beyond movement and can br...",Yoga Block,Meditation 22,RIOPY,https://members.onepeloton.com/classes/bootcam...
1,54ac61803b364b2fa8378acd9f593cdb,15 min Bodyweight Strength,"No equipment, no problem. Join us for a high-e...",5.7755,15,Strength,19,psny-studio-3,2021-09-03 13:19:00,0.9933,297,Olivia Amato,"Born and raised in New York, Olivia grew up pl...",Workout Mat,"California Gurls,Let's Get Loud,Let It Rock (f...","Katy Perry,Snoop Dogg,Jennifer Lopez,Kevin Rud...",https://members.onepeloton.com/classes/bootcam...
2,c75fd4831573483c9d45739aae11d083,20 min Focus Flow: Lower Body,This yoga flow class focuses on poses that eng...,4.3664,20,Yoga,23,psny-studio-2,2021-09-03 12:51:00,1.0000,159,Aditi Shah,"To Aditi, yoga goes beyond movement and can br...","Yoga Blanket,Yoga Block,Yoga Mat","Interlude No 1,Oceansize,She Just Likes To Fig...","James Vincent McMorrow,Oh Wonder,Four Tet,Grim...",https://members.onepeloton.com/classes/bootcam...
3,470086936f7a4723ab5a53cb80b571ff,45 min Pop Bootcamp,Split your workout 50/50 between cardio on the...,7.8312,45,Tread Bootcamp,50,psny-studio-4,2021-09-03 11:56:00,0.9737,152,Olivia Amato,"Born and raised in New York, Olivia grew up pl...","Workout Mat,Medium Weights",34+35 (Remix) (feat. Doja Cat & Megan Thee Sta...,"Ariana Grande,Doja Cat,Megan Thee Stallion,Jus...",https://members.onepeloton.com/classes/bootcam...
4,9680a817bf2149d2b91990c87166a400,20 min Pop Ride,We dare you not to dance as you ride to all th...,7.4000,20,Cycling,24,uk,2021-09-03 07:52:00,1.0000,82,Sam Yo,Sam is a pro at many things but shines when it...,None,"Señorita,Marry You,Irreplaceable,What Do You M...","Justin Timberlake,Bruno Mars,Beyoncé,Justin Bi...",https://members.onepeloton.com/classes/bootcam...

In [3]:
# Opening pickle files
# Use classId where you can as key for merging
base_clean_df = pd.read_pickle("./base_clean_df.pkl")
artist_df = pd.read_pickle("./artist_df.pkl")
artist_id_class_count = pd.read_pickle("larger_spot_artist_id_class_count.pkl")
songs_df = pd.read_pickle("./songs_df.pkl")
song_class_count_df = pd.read_pickle("./song_class_count_df.pkl")
song_class_count_df.rename(columns={'Artist':'Song'}, inplace=True) # Quick clean rename column
class_type_reorg_df = pd.read_pickle("./class_type_reorg_df.pkl")
new_class_types_with_artists = pd.read_pickle("./new_class_types_with_artists.pkl")
master_song_df = pd.read_pickle("./master_song_df.pkl")
# artist_id_class_count has 186 rows with 0LyfQWJT6nXafLPZqxe9Of - it means Various Artists
# and 40 errors

In [4]:
base_clean_df.head()
# Difference from df:
# Dropped null 'instructorBio' rows - only 9
# Dropped rows with null classSongs/classArtists
# Dropped row value with classSongs as float (1 row)
# Populate rows with classType Cycling and classEquipment None to classEquipment = Bike

,classId,className,classDescription,classDifficulty,classDuration,classType,classLength,classLocation,classOriginalAirdate,classRating,classRatingCount,instructorName,instructorBio,classEquipment,classSongs,classArtists,classUrl
0,7f66378211c9476b9b5619bf989f91d0,20 min Peace Meditation,A guided meditation that focuses on cultivatin...,4.3333,20,Meditation,23,psny-studio-2,2021-09-03 13:25:00,0.9847,131,Aditi Shah,"To Aditi, yoga goes beyond movement and can br...",Yoga Block,Meditation 22,RIOPY,https://members.onepeloton.com/classes/bootcam...
1,54ac61803b364b2fa8378acd9f593cdb,15 min Bodyweight Strength,"No equipment, no problem. Join us for a high-e...",5.7755,15,Strength,19,psny-studio-3,2021-09-03 13:19:00,0.9933,297,Olivia Amato,"Born and raised in New York, Olivia grew up pl...",Workout Mat,"California Gurls,Let's Get Loud,Let It Rock (f...","Katy Perry,Snoop Dogg,Jennifer Lopez,Kevin Rud...",https://members.onepeloton.com/classes/bootcam...
2,c75fd4831573483c9d45739aae11d083,20 min Focus Flow: Lower Body,This yoga flow class focuses on poses that eng...,4.3664,20,Yoga,23,psny-studio-2,2021-09-03 12:51:00,1.0000,159,Aditi Shah,"To Aditi, yoga goes beyond movement and can br...","Yoga Blanket,Yoga Block,Yoga Mat","Interlude No 1,Oceansize,She Just Likes To Fig...","James Vincent McMorrow,Oh Wonder,Four Tet,Grim...",https://members.onepeloton.com/classes/bootcam...
3,470086936f7a4723ab5a53cb80b571ff,45 min Pop Bootcamp,Split your workout 50/50 between cardio on the...,7.8312,45,Tread Bootcamp,50,psny-studio-4,2021-09-03 11:56:00,0.9737,152,Olivia Amato,"Born and raised in New York, Olivia grew up pl...","Workout Mat,Medium Weights",34+35 (Remix) (feat. Doja Cat & Megan Thee Sta...,"Ariana Grande,Doja Cat,Megan Thee Stallion,Jus...",https://members.onepeloton.com/classes/bootcam...
4,9680a817bf2149d2b91990c87166a400,20 min Pop Ride,We dare you not to dance as you ride to all th...,7.4000,20,Cycling,24,uk,2021-09-03 07:52:00,1.0000,82,Sam Yo,Sam is a pro at many things but shines when it...,Bike,"Señorita,Marry You,Irreplaceable,What Do You M...","Justin Timberlake,Bruno Mars,Beyoncé,Justin Bi...",https://members.onepeloton.com/classes/bootcam...

Note:
classId = 8840f82cdc624aa28a5d1babc51a3916 is the one you need to watch out for (has float classSong)

In [5]:
# Check lengths of dfs
print(f'artist_df: {len(artist_df)}')
print(f'artist_id_class_count: {len(artist_id_class_count)}')
print(f'songs_df: {len(songs_df)}')
print(f'master_song_df: {len(master_song_df)}')
print(f'class_type_reorg_df: {len(class_type_reorg_df)}')
print(f'new_class_types_with_artists: {len(new_class_types_with_artists)}')
# No inconsistencies where there shouldn't be

artist_df: 16748
artist_id_class_count: 10941
songs_df: 16748
master_song_df: 29904
class_type_reorg_df: 16748
new_class_types_with_artists: 16748

#### Notes:
- artist_df has a row for each of the 16748 classes with the lists of artists in that class and 10943 columns
    - column for classId, classArtists (from base_clean_df)
    - then each of the 10941 artists

- artist_id_class_count has 10941 rows for each of the artists with their class count, followers, genres, popularity
    - keep in mind nulls not cleaned yet...
    - keep them in there until you decide what you're doing with the data
    - can clean after merging with final data set

#### Playing with Class Info

In [26]:
class_df = base_clean_df['className'].to_frame()

In [27]:
class_df['className'][0].split('min ')[1]
# Split this off into new column and see if you can parse themes

'Peace Meditation'

# ^Split this off into new column and see if you can parse themes

### Spotify API Work

In [6]:
# Spotify API set up
# Source: https://betterprogramming.pub/how-to-extract-any-artists-data-using-spotify-s-api-python-and-spotipy-4c079401bc37
client_id = '4aac5b215c8a4fc591b506b71af7ebf5'
client_secret = '31d999b609424f569382b047ba828b00'

client_credentials_manager = SpotifyClientCredentials(client_id, client_secret)
sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager)

#### Notes:
- Try marrying artist info to base_clean_df first
- When you join, you may need to apply same cleansing steps to the column in base_clean_df for matching

Joining notes
- Final df should have a line for each artist. This means the class data would be duplicated...
- Could you join artist id with classes, then if 

- artist_df joined with base_clean_df would give you artists in class
    - how could this be used to join artist level data
    - add artist columns to joined df (artist_df and base_clean_df), then if artist column = 1 fill in the columns with the artist information?
    - BUT there will be multiple artists

In [10]:
artist_df
# this

,classId,classArtists,Charles Lloyd,Marshall Jefferson,Electric Six,Bjonr,Gerald Alston,Blue Cheer,Madden,Jessy,...,Maxence Cyrin,B.B. Jay,Yizzy,Bellman,Lauren Pritchard,The Japanese Popstars,James Jacob,Radio Remix,Mayer Hawthorne,John Ryan
0,7f66378211c9476b9b5619bf989f91d0,[RIOPY],0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,54ac61803b364b2fa8378acd9f593cdb,"[Katy Perry, Snoop Dogg, Jennifer Lopez, Kevin...",0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,c75fd4831573483c9d45739aae11d083,"[James Vincent McMorrow, Oh Wonder, Four Tet, ...",0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,470086936f7a4723ab5a53cb80b571ff,"[Ariana Grande, Doja Cat, Megan Thee Stallion,...",0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,9680a817bf2149d2b91990c87166a400,"[Justin Timberlake, Bruno Mars, Beyoncé, Justi...",0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16743,a144fcf1595740caa610f6484deb3cdb,"[Guts, Leron Thomas, Soopasoul, FDEL, Basement...",0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16744,bd89a56c884b48e59ce9c43ab4f4d86f,"[Next, Boyz II Men, Blues Traveler, Eagle-Eye ...",0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16745,e5a99c83d7fc4f0686c68b02e5932204,"[Daphne Willis, Gizzle, Lo Air, Sigala, Ella E...",0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16746,c57e123004d04df1bfae94c5e4399bb3,"[Robyn, No Doubt, C & C Music Factory, Technot...",0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16747,62ea77fe28fa4b049465b0d6ded022e0,"[Keljet, AVAN LAVA, Oliver Nelson, Gigamesh, C...",0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
artist_id_class_count

,name,Class Count,id,followers,genres,popularity
0,ACE HOOD,1,NaN,NaN,NaN,NaN
1,AKON,1,NaN,NaN,NaN,NaN
2,Cambridge,1,NaN,NaN,NaN,NaN
3,Cr3on,6,NaN,NaN,NaN,NaN
4,DJ Deeon,13,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
10936,yutaka hirasaka,1,0stmdx2IonUUUIlWQ9bLYZ,12363.0,"['j-ambient', 'japanese guitar', 'japanese jaz...",52.0
10937,Álvaro Faria,4,3Vop0LjMsp1743VPBhYJXl,NaN,NaN,NaN
10938,Ásgeir,12,7xUZ4069zcyBM4Bn10NQ1c,252028.0,"['icelandic folk', 'icelandic indie', 'iceland...",60.0
10939,Ådå,1,0Ll3Su2buPphrFk5OdPEvp,1176.0,[],32.0
10940,Ólafur Arnalds,212,7E3BRXV9ZbCt5lQTCXMTia,586682.0,"['bow pop', 'compositional ambient', 'icelandi...",70.0